Translate: Dom Manipulation(~ Document Interface)
typescript-kr/typescript-kr.github.io pull request #150
Opened 2020-08-18 16:28 UTC by ss-won

reference: #117 

처음 ~ The Document Interface 부분까지 번역 완료했습니다.
일단, 한글로 번역하기 애매한 용어 부분은 대체로 원어 그대로 사용하였습니다.

번역하다가 가장 애매했던 부분은 다음과 같습니다.

1. `line74`의 `_deprecated_` 를 번역하기 애매해서 deprecated 표기라고 번역했는데, 더 좋은 표현이 있으면 제안 부탁드립니다.
2. `line102`에서 `Which is exactly what happens;` 부분이 무슨 말인지 모르겠어서 일단, 문맥상 제가 생각하기에 어울리는 말로 번역했습니다.
3. `HTMLElement` type 표현이 많이 나오는데, TypeScript에 정의된 Interface 부분이라 생각해서 번역 용어에 따라 타입이 아닌 유형으로 번역했는데 이 부분이 적절한지 잘 모르겠습니다. 

검토해주시고 의역과 오역, 또는 제안 사항 부탁드립니다! 🙇🏻‍♀️

2020-08-18 19:33 UTC, dvlprsh commented on pages/tutorials/dom-manipulation.md
> +### _`HTMLElement` 유형 탐구_ (_An exploration into the `HTMLElement` type_)
```suggestion
### _`HTMLElement` 타입 탐구_ (_An exploration into the `HTMLElement` type_)
```

> 3. `HTMLElement` type 표현이 많이 나오는데, TypeScript에 정의된 Interface 부분이라 생각해서 번역 용어에 따라 타입이 아닌 유형으로 번역했는데 이 부분이 적절한지 잘 모르겠습니다.

[wiki 번역 용어집](https://github.com/typescript-kr/typescript-kr.github.io/wiki/%EB%B2%88%EC%97%AD-%EC%9A%A9%EC%96%B4%EC%A7%91) 에 `type`-> `타입`으로 정의되어 있습니다 :)

2020-08-18 20:41 UTC, dvlprsh commented on pages/tutorials/dom-manipulation.md
> +주어진 _index.html_ 간소화 파일:
[제안]
```suggestion
간단한 예시 파일 _index.html_:
```

2020-08-18 20:41 UTC, dvlprsh commented on pages/tutorials/dom-manipulation.md
> +이는 오버 로드된 함수 정의입니다. 두 번째 오버로드는 가장 단순하며 `getElementById` 메서드와 매우 유사하게 작동합니다. 어떤 `문자열`이 전달되면 HTMLElement 표준이 반환됩니다. 이 정의는 개발자들이 고유한 HTML 요소 태그들을 생성할 수 있게 합니다.
```suggestion
이는 오버 로드된 함수 정의입니다. 두 번째 오버로드는 가장 단순하며 `getElementById` 메서드와 매우 유사하게 작동합니다. 어떤 `문자열`이 전달되면 HTMLElement 표준이 반환됩니다. 이 정의는 개발자가 고유한 HTML 요소 태그를 생성할 수 있게 합니다.
```

2020-08-18 20:41 UTC, dvlprsh commented on pages/tutorials/dom-manipulation.md
> +`createElement`의 첫 번째 정의에는, 고급 일반 패턴들을 사용하고 있습니다. 이는 내용을 나누어 이해하는 것이 가장 좋습니다. 먼저 `<K extends keyof HTMLElementTagNameMap>`라는 일반적인 표현부터 시작합니다. 이 표현식은 `HTMLElementTagNameMap` 인터페이스의 키에 제약을 받는 일반적인 매개변수
```suggestion
`createElement`의 첫 번째 정의에는, 고급 제네릭 패턴을 사용하고 있습니다. 이는 내용을 나누어 이해하는 것이 가장 좋습니다. 먼저 `<K extends keyof HTMLElementTagNameMap>`라는 제네릭 표현부터 시작합니다. 이 표현식은 `HTMLElementTagNameMap` 인터페이스의 키에 제약을 받는 제네릭 매개변수 `K`를 정의하고 있습니다. 그 맵 인터페이스는 모든 지정된 HTML 태그 이름과 해당 타입 인터페이스를 포함하고 있습니다. 예를 들면 여기 코드 초반에 5개의 매핑된 값이 있습니다:
```
TypeScript에 `generic`이라는 개념이 있습니다. 여기서는 그 용어로 쓰인거 같네요 :) [참고 자료](https://typescript-kr.github.io/pages/generics.html)

2020-08-18 20:41 UTC, dvlprsh commented on pages/tutorials/dom-manipulation.md
> +이제, `createElement` 정의의 나머지 부분인 `(tagName: K, options?: ElementCreationOptions): HTMLElementTagNameMap[K]`를 살펴보겠습니다. 첫 번째 인수 `tagName`은 일반적 매개변수 `K`로 정의됩니다. TypeScript 인터프리터는 이 인수로부터 일반 매개변수를 _추론_ 할
```suggestion
이제, `createElement` 정의의 나머지 부분인 `(tagName: K, options?: ElementCreationOptions): HTMLElementTagNameMap[K]`를 살펴보겠습니다. 첫 번째 인수 `tagName`은 제네릭 매개변수 `K`로 정의됩니다. TypeScript 인터프리터는 이 인수로부터 제네릭 매개변수를 _추론_ 할 수 있는 충분한 성능을 가지고 있습니다. 이는 개발자가 메서드를 사용할 때 실제로 제네릭 매개변수를 지정할 필요가 없음을 의미하며, 어떤 값이 `tagName`인수로 전달되든 간에 `K`로 추론되므로 정의의 나머지 부분에 사용할 수 있을 것입니다. 정확히 무슨 일이 일어나는지를 보면 반환값 `HTMLElementTagNameMap[K]`는 `tagName`인수를 가지고 해당 타입을 반환합니다. 이 정의는 스니펫 코드 `p` 변수에서 `HTMLParagraphElement`타입을 얻는 방법입니다. 그리고 코드가 `document.createElement('a')`였다면, `HTMLAnchorElement`타입의 요소가 됩니다.
```

2020-08-18 20:41 UTC, dvlprsh commented on pages/tutorials/dom-manipulation.md
> +문자열 id 요소가 전달되면 `HTMLElement` 또는 `null`이 반환됩니다. 이 메서드는 가장 중요한 유형들 중 하나인 `HTMLElement`를 도입합니다. 이 유형은 다른 모든 요소 인터페이스의 기본 인터페이스 역할을 합니다. 예를 들면, 예제 코드에서 `p` 변수는 `HTMLParagraphElement` 유형입니다. 다음으로, 이 메서드는
```suggestion
문자열 id 요소가 전달되면 `HTMLElement` 또는 `null`이 반환됩니다. 이 메서드는 가장 중요한 타입 중 하나인 `HTMLElement`를 도입합니다. 이 유형은 다른 모든 요소 인터페이스의 기본 인터페이스 역할을 합니다. 예를 들면, 예제 코드에서 `p` 변수는 `HTMLParagraphElement` 타입입니다. 다음으로, 이 메서드는 `null`을 반환할 수 있다는 점에 유의해야 합니다. 메서드가 실제로 지정된 요소를 찾을 수 있을지 없을지에 따라 확실한 사전 런타임이 될 수 없기 때문입니다. 스니펫 코드의 마지막 줄에는, `appendChild`를 호출하기 위해 새로운 _optional chaining_ 연산자가 사용되고 있습니다.
```

2020-08-18 20:42 UTC, dvlprsh commented
> 1. `line74`의 `_deprecated_` 를 번역하기 애매해서 deprecated 표기라고 번역했는데, 더 좋은 표현이 있으면 제안 부탁드립니다.
> 2. `line102`에서 `Which is exactly what happens;` 부분이 무슨 말인지 모르겠어서 일단, 문맥상 제가 생각하기에 어울리는 말로 번역했습니다.
> 3. `HTMLElement` type 표현이 많이 나오는데, TypeScript에 정의된 Interface 부분이라 생각해서 번역 용어에 따라 타입이 아닌 유형으로 번역했는데 이 부분이 적절한지 잘 모르겠습니다.

1, 2. 괜찮은거 같습니다ㅎㅎ
3. [wiki 번역 용어집](https://github.com/typescript-kr/typescript-kr.github.io/wiki/%EB%B2%88%EC%97%AD-%EC%9A%A9%EC%96%B4%EC%A7%91) 에 `type`-> `타입`으로 정의되어 있습니다 :)

2020-08-19 01:31 UTC, guyeol commented on pages/tutorials/dom-manipulation.md
> +표준화 이후 20여 년 동안, JavaScript는 매우 많은 발전을 이루었습니다. 2020년에는 서버, 데이터 사이언스, 그리고 IoT 기기에도 JavaScript를 사용할 수 있지만, 가장 인기 있는 활용 사례는 웹 브라우저인 것을 기억하는 것이 중요합니다.
```suggestion
표준화 이후 20여 년 동안, JavaScript는 많은 발전을 이루었습니다. 2020년에는 서버, 데이터 사이언스, 그리고 IoT 기기에도 JavaScript를 사용할 수 있지만, 가장 인기 있는 활용 사례는 웹 브라우저인 것을 기억하는 것이 중요합니다.
```
[제안]

2020-08-19 01:34 UTC, guyeol commented on pages/tutorials/dom-manipulation.md
> +TypeScript 코드의 첫 번째 줄은 전역변수 `document`를 사용하며, 그 변수를 검사하면 _lib.dom.d.ts_ 파일의 `Document` 인터페이스에 의해 정의된 것으로 표시됩니다. 그 코드의 스니펫(snippet)에는 `getElementById`와 `createElement`라는 두 개의 메서드 호출이 포함되어 있습니다.
```suggestion
TypeScript 코드의 첫 번째 줄은 전역변수 `document`를 사용하며, 그 변수를 검사하면 _lib.dom.d.ts_ 파일의 `Document` 인터페이스에 의해 정의된 것으로 표시됩니다. 그 코드의 스니펫(snippet)에는 `getElementById`와 `createElement`라는 두 가지 메서드 호출이 포함되어 있습니다.
```
[제안]

2020-08-19 01:36 UTC, guyeol commented on pages/tutorials/dom-manipulation.md
> +문자열 id 요소가 전달되면 `HTMLElement` 또는 `null`이 반환됩니다. 이 메서드는 가장 중요한 유형들 중 하나인 `HTMLElement`를 도입합니다. 이 유형은 다른 모든 요소 인터페이스의 기본 인터페이스 역할을 합니다. 예를 들면, 예제 코드에서 `p` 변수는 `HTMLParagraphElement` 유형입니다. 다음으로, 이 메서드는
```suggestion
문자열 id 요소가 전달되면 `HTMLElement` 또는 `null`이 반환됩니다. 이 메서드는 가장 중요한 유형들 중 하나인 `HTMLElement`를 도입합니다. 이 유형은 다른 모든 요소 인터페이스의 기본 인터페이스 역할을 합니다. 예를 들면, 예제 코드에서 `p` 변수는 `HTMLParagraphElement` 유형입니다. 다음으로, 이 메서드는 `null`을 반환할 수 있다는 점에 유의해야 합니다. 메서드가 실제로 지정된 요소를 찾을 수 있을지 없을지에 따라 확실한 사전 런타임이 될 수 없기 때문입니다. 스니펫 코드의 마지막 줄에는, `appendChild`를 호출하기 위해 새로운 _선택적 체이닝 (optional chaining)_ 연산자가 사용되고 있습니다.
```
[제안]

2020-08-19 01:48 UTC, guyeol commented
> 1. line74의 _deprecated_ 를 번역하기 애매해서 deprecated 표기라고 번역했는데, 더 좋은 표현이 있으면 제안 부탁드립니다.
> 2. line102에서 Which is exactly what happens; 부분이 무슨 말인지 모르겠어서 일단, 문맥상 제가 생각하기에 어울리는 말로 번역했습니다.
> 3. HTMLElement type 표현이 많이 나오는데, TypeScript에 정의된 Interface 부분이라 생각해서 번역 용어에 따라 타입이 아닌 유형으로 번역했는데 이 부분이 적절한지 잘 모르겠습니다.
1. `deprecated` 그대로 사용해도 좋을 것 같네요!
2. 번역 잘 하신거 같습니다 😄
3. 여기에서는 `타입`이 더 적절해보입니다

2020-08-19 13:21 UTC, ss-won commented on pages/tutorials/dom-manipulation.md
> +웹 사이트는 HTML 및/또는 XML 문서로 구성됩니다. 이러한 문서들은 정적이어서, 변하지 않습니다. *문서 객체 모델(DOM)은* 정적 웹 사이트를 기능적으로 작동시키기 위해 브라우저에 의해 구현된 프로그래밍 인터페이스입니다. DOM API를 사용하면 문서의 구조, 스타일, 그리고 내용을 변경할 수 있습니다. API는 매우 강력하기 때문에 그 주변에서
말씀주신 제안이 훨씬 좋네요 👍 
정말 한끗 차이긴 한데 마지막에 동적 웹사이트를 개발하기 위한 수많은 부분이 조금 부자연스러운데 아래와 같이 해도 괜찮을까요 ?,?
```suggestion
웹 사이트는 HTML 및/또는 XML 문서로 구성됩니다. 이러한 문서들은 정적이어서, 변하지 않습니다. *문서 객체 모델(DOM)은* 정적 웹 사이트를 기능적으로 작동시키기 위해 브라우저에 의해 구현된 프로그래밍 인터페이스입니다. DOM API를 사용하면 문서의 구조, 스타일, 그리고 내용을 변경할 수 있습니다. API는 매우 강력해서 이를 바탕으로 보다 쉽게 동적인 웹사이트를 개발하기 위해 수많은 프런트엔드 프레임워크(jQuery, React, Angular, 등)가 개발되었습니다.
```

2020-08-19 13:24 UTC, ss-won commented on pages/tutorials/dom-manipulation.md
> +주어진 _index.html_ 간소화 파일:
수정했습니다 🙇🏻‍♀️

2020-08-19 13:26 UTC, ss-won commented on pages/tutorials/dom-manipulation.md
> +`createElement`의 첫 번째 정의에는, 고급 일반 패턴들을 사용하고 있습니다. 이는 내용을 나누어 이해하는 것이 가장 좋습니다. 먼저 `<K extends keyof HTMLElementTagNameMap>`라는 일반적인 표현부터 시작합니다. 이 표현식은 `HTMLElementTagNameMap` 인터페이스의 키에 제약을 받는 일반적인 매개변수
자료 감사합니다! ☺️ 수정했습니다!

2020-08-19 13:38 UTC, dvlprsh commented on pages/tutorials/dom-manipulation.md
> +웹 사이트는 HTML 및/또는 XML 문서로 구성됩니다. 이러한 문서들은 정적이어서, 변하지 않습니다. *문서 객체 모델(DOM)은* 정적 웹 사이트를 기능적으로 작동시키기 위해 브라우저에 의해 구현된 프로그래밍 인터페이스입니다. DOM API를 사용하면 문서의 구조, 스타일, 그리고 내용을 변경할 수 있습니다. API는 매우 강력하기 때문에 그 주변에서
넵 @ss-won님이 최종 수정해 주신게 자연스러운 거 같습니다 👍 😄

2020-08-19 13:45 UTC, ss-won commented on pages/tutorials/dom-manipulation.md
> +TypeScript 코드의 첫 번째 줄은 전역변수 `document`를 사용하며, 그 변수를 검사하면 _lib.dom.d.ts_ 파일의 `Document` 인터페이스에 의해 정의된 것으로 표시됩니다. 그 코드의 스니펫(snippet)에는 `getElementById`와 `createElement`라는 두 개의 메서드 호출이 포함되어 있습니다.
훨씬 매끄럽네요 수정했습니다! ☺️

2020-08-19 13:50 UTC, yeonjuan requested changes

2020-08-19 13:50 UTC, yeonjuan commented on pages/tutorials/dom-manipulation.md
> +이제, `createElement` 정의의 나머지 부분인 `(tagName: K, options?: ElementCreationOptions): HTMLElementTagNameMap[K]`를 살펴보겠습니다. 첫 번째 인수 `tagName`은 일반적 매개변수 `K`로 정의됩니다. TypeScript 인터프리터는 이 인수로부터 일반 매개변수를 _추론_ 할
```suggestion
이제, `createElement` 정의의 나머지 부분인 `(tagName: K, options?: ElementCreationOptions): HTMLElementTagNameMap[K]`를 살펴보겠습니다. 첫 번째 인수 `tagName`은 제네릭 매개변수 `K`로 정의됩니다. TypeScript 인터프리터는 이 인수로부터 제네릭 매개변수를 _추론_ 할 수 있는 충분한 성능을 가지고 있습니다. 이는 개발자가 메서드를 사용할 때 실제로 제네릭 매개변수를 지정할 필요가 없음을 의미하며, 어떤 값이 `tagName`인수로 전달되든 간에 `K`로 추론되므로 정의의 나머지 부분에 사용할 수 있을 것입니다. 정확히 무슨 일이 일어나는지를 보면 반환값 `HTMLElementTagNameMap[K]`는 `tagName`인수를 가지고 해당 타입을 반환합니다. 이 정의는 스니펫 코드 `p` 변수에서 `HTMLParagraphElement`타입을 얻는 방법입니다. 그리고 코드가 `document.createElement('a')`였다면, `HTMLAnchorElement`타입의 요소가 됩니다.
```

2020-08-19 13:50 UTC, yeonjuan commented on pages/tutorials/dom-manipulation.md
> +이제, `createElement` 정의의 나머지 부분인 `(tagName: K, options?: ElementCreationOptions): HTMLElementTagNameMap[K]`를 살펴보겠습니다. 첫 번째 인수 `tagName`은 일반적 매개변수 `K`로 정의됩니다. TypeScript 인터프리터는 이 인수로부터 일반 매개변수를 _추론_ 할
@ss-won 번역 감사합니다 👍 여기서는 일반적이 아니라 제네릭으로 번역하는게 맞는 것 같아요 ㅎㅎ

아래와 같은 제네릭 추론 능력을 말하고 있는것 같아서요 ㅎㅎ

```ts
function foo<T> (a: T): T {
  return a;
}

foo(1); // 과 같이 사용하면 a 가 T(number) 로 추론
foo("@"); // 같이 사용하면 a 가 T(string) 으로 추론
``

2020-08-19 13:56 UTC, ss-won commented on pages/tutorials/dom-manipulation.md
> +이제, `createElement` 정의의 나머지 부분인 `(tagName: K, options?: ElementCreationOptions): HTMLElementTagNameMap[K]`를 살펴보겠습니다. 첫 번째 인수 `tagName`은 일반적 매개변수 `K`로 정의됩니다. TypeScript 인터프리터는 이 인수로부터 일반 매개변수를 _추론_ 할
네! 수정했습니다 🙇🏻‍♀️

2020-08-19 13:59 UTC, yeonjuan approved these changes
👍 👍 고생하셨습니다

2020-08-19 14:59 UTC, dvlprsh approved these changes
고생하셨습니다 👍

2020-08-19 14:59 UTC, merged

2020-08-19 15:00 UTC, dvlprsh commented
@all-contributors please add @ss-won for translation