환경 변수 `TSC_WATCHFILE`을 사용하여 파일 감시 설정 표 번역 완료
typescript-kr/typescript-kr.github.io pull request #165
Opened 2020-08-24 11:04 UTC by whoo3474

수정요청 온것 수정하였으며, 나머지 번역 지금 작업중입니다. :)

2020-08-24 13:30 UTC, whoo3474 commented
아이고야.. 영어가 어색하고 환경설정 하는 부분들이 어색해서 한참을 뚫어져라 보는데도 이 정도가 한계였네요..ㅠ
많은 지도 편달 부탁드리겠습니다...!

2020-08-27 15:50 UTC, yeonjuan requested changes
번역 감사합니다!! 
2가지 오타로 보이는 부분 빼고, 나머지는 좋은 것 같아요 :) 감사합니다 ( _ _ )

2020-08-27 15:50 UTC, yeonjuan commented on pages/configuring-watch.md
> +옵션                                            | 설정
```suggestion
옵션                                            | 설명
```

2020-08-27 15:50 UTC, yeonjuan commented on pages/configuring-watch.md
> +`UseFsEventsOnParentDirectory`                 | 이 옵션은 'fs.watch'(파일 시스템 이벤트 사용하는)로 파일의 상위 디렉터리를 감시합니다. 다만, CPU 사용량이 늘어나고 정확도는 떨어질 수 있습니다.
```suggestion
`UseFsEventsOnParentDirectory`                 | 이 옵션은 `fs.watch`(파일 시스템 이벤트 사용하는)로 파일의 상위 디렉터리를 감시합니다. 다만, CPU 사용량이 늘어나고 정확도는 떨어질 수 있습니다.
```

2020-08-27 15:50 UTC, yeonjuan commented on pages/configuring-watch.md
> +옵션                                            | 설정
```suggestion
옵션                                            | 설명
```

2020-08-31 15:03 UTC, guyeol reviewed
몇 가지 제안 남겨두었습니다 👍

2020-08-31 15:03 UTC, guyeol commented on pages/configuring-watch.md
> +`fs.watchFile`은 폴링을 사용하므로 CPU cycles가 필요합니다만, 파일/디렉터리 상태에 대한 업데이트를 받을 수 있는 가장 신뢰할 수 있는 메커니즘입니다. 컴파일러는 일반적으로 `fs.watchFile`을 사용하여 소스 파일, 구성 파일 및 누락된 파일(누락된 파일 참조)을 감시합니다. 이는 CPU 사용량이 프로그램의 파일 수에 따라 달라
```suggestion
`fs.watchFile`은 폴링을 사용하므로 CPU 주기를 포함합니다. 하지만 이는 파일/디렉터리 상태에 대한 업데이트를 받을 수 있는 가장 신뢰할 수 있는 메커니즘입니다. 컴파일러는 일반적으로 `fs.watchFile`을 사용하여 소스 파일, 구성 파일 및 누락된 파일(누락된 파일 참조)을 감시하는데 이는 CPU 사용량이 프로그램의 파일 수에 따라 달라진다는 것을 의미합니다.
```
[제안]

2020-09-01 00:26 UTC, whoo3474 commented on pages/configuring-watch.md
> +`fs.watchFile`은 폴링을 사용하므로 CPU cycles가 필요합니다만, 파일/디렉터리 상태에 대한 업데이트를 받을 수 있는 가장 신뢰할 수 있는 메커니즘입니다. 컴파일러는 일반적으로 `fs.watchFile`을 사용하여 소스 파일, 구성 파일 및 누락된 파일(누락된 파일 참조)을 감시합니다. 이는 CPU 사용량이 프로그램의 파일 수에 따라 달라
감사합니다. :)

2020-09-01 00:26 UTC, whoo3474 commented on pages/configuring-watch.md
> +옵션                                            | 설정
감사합니다. :)

2020-09-09 10:57 UTC, guyeol commented
@whoo3474 님 현재 제안들 resolve 해주시면 승인하겠습니다!

2020-09-09 12:28 UTC, whoo3474 commented
> @whoo3474 님 현재 제안들 resolve 해주시면 승인하겠습니다!

지금 다시 반영하였습니다. :)

2020-09-10 08:10 UTC, guyeol approved these changes

2020-09-10 09:55 UTC, dvlprsh approved these changes

2020-09-10 09:56 UTC, dvlprsh commented
@all-contributors please add @whoo3474 for translation

2020-09-10 10:00 UTC, merged